[[plugins]]
repo = 'flazz/vim-colorschemes'

[[plugins]]
repo = 'atelierbram/Base2Tone-vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_source = '''
autocmd FileType denite call s:denite_my_settings()
function! s:denite_my_settings() abort
  nnoremap <silent><buffer><expr> <CR>
  \ denite#do_map('do_action')
  nnoremap <silent><buffer><expr> d
  \ denite#do_map('do_action', 'delete')
  nnoremap <silent><buffer><expr> p
  \ denite#do_map('do_action', 'preview')
  nnoremap <silent><buffer><expr> q
  \ denite#do_map('quit')
  nnoremap <silent><buffer><expr> i
  \ denite#do_map('open_filter_buffer')
  nnoremap <silent><buffer><expr> <Space>
  \ denite#do_map('toggle_select').'j'
endfunction
  nnoremap [denite] <Nop>
  nmap <space>d [denite]
  nnoremap [denite]f :Denite file/rec<cr>
  nnoremap [denite]h :Denite help<cr>
  nnoremap [denite]b :Denite buffer<cr>
'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'skywind3000/asyncrun.vim'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'easymotion/vim-easymotion'

[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'
hook_source = '''
  let g:indent_guides_enable_on_vim_startup = 1
'''

[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'
depends = ['nerdtree', 'vim-fugitive']
hook_source = '''
  let g:NERDTreeHijackNetrw = 0
  noremap <space>n :NERDTreeToggle<cr>
'''

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_source = '''
  let g:lightline = {
        \ 'colorscheme': 'wombat',
        \ 'active': {
        \   'left': [ [ 'mode', 'paste' ],
        \             [ 'fugitive', 'readonly', 'filename', 'modified' ] ]
        \},
        \ 'component': {
        \   'readonly': '%{&filetype=="help"?"":&readonly?"?":""}',
        \   'modified': '%{&filetype=="help"?"":&modified?"+":&modifiable?"":"-"""}',
        \   'fugitive': '%{exists("*fugitive#head")?fugitive#head():""}'
        \},
        \ 'component_visible_condition': {
        \   'readonly': '(&filetype!="help"&& &readonly)',
        \   'modified': '(&filetype!="help"&&(&modified||!&modifiable))',
        \   'fugitive': '(exists("*fugitive#head") && ""!=fugitive#head())'
        \ },
        \ 'separator': { 'left': '>', 'right': '<' },
        \ 'subseparator': { 'left': '>', 'right': '<' }
        \ }
'''
[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'vim-scripts/myprojects'
hook_source = '''
  let g:myprojects_auto_open = 0
  noremap <silent><leader><leader>p :MyProjectsToggle<cr>
'''

[[plugins]]
repo = 'vim-scripts/tabpage.vim'

[[plugins]]
repo = 't9md/vim-quickhl' 
hook_source = '''
  nmap <Space>m <Plug>(quickhl-manual-this)
  xmap <Space>m <Plug>(quickhl-manual-this)
  nmap <Space>M <Plug>(quickhl-manual-reset)
  xmap <Space>M <Plug>(quickhl-manual-reset)
  let g:quickhl_manual_colors = [
          \ "gui=bold ctermfg=7   ctermbg=1   guibg=#a07040 guifg=#ffffff",
          \ "gui=bold ctermfg=7   ctermbg=2   guibg=#4070a0 guifg=#ffffff",
          \ "gui=bold ctermfg=7   ctermbg=3   guibg=#40a070 guifg=#ffffff",
          \ "gui=bold ctermfg=7   ctermbg=4   guibg=#70a040 guifg=#ffffff",
          \ "gui=bold ctermfg=7   ctermbg=5   guibg=#0070e0 guifg=#ffffff",
          \ "gui=bold ctermfg=7   ctermbg=6   guibg=#007020 guifg=#ffffff",
          \ "gui=bold ctermfg=7   ctermbg=21  guibg=#d4a00d guifg=#ffffff",
          \ "gui=bold ctermfg=7   ctermbg=22  guibg=#06287e guifg=#ffffff",
          \ "gui=bold ctermfg=7   ctermbg=45  guibg=#5b3674 guifg=#ffffff",
          \ "gui=bold ctermfg=7   ctermbg=16  guibg=#4c8f2f guifg=#ffffff",
          \ "gui=bold ctermfg=7   ctermbg=50  guibg=#1060a0 guifg=#ffffff",
          \ "gui=bold ctermfg=7   ctermbg=56  guibg=#a0b0c0 guifg=black",
          \ ]
'''

[[plugins]]
repo = 'cohama/lexima.vim'

[[plugins]]
repo = 'tpope/vim-repeat'
on_idle = 1

[[plugins]]
repo = 'tpope/vim-speeddating'

[[plugins]]
repo = 'joonty/vdebug'

[[plugins]]
repo = 'vim-scripts/dbext.vim'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'mattn/vim-gist'
depends = 'mattn/webapi-vim'
hook_source = '''
  let g:github_user='[username]'
  let g:gist_token='[personal access tokens]'
'''

[[plugins]]
repo = 'machakann/vim-highlightedyank'
hook_source = '''
  let g:highlightedyank_highlight_duration = 100
'''
