[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = ['python']
depends = ['deoplete']

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = ['python']
hook_source = '''
  let g:jedi#auto_initialization = 1
  let g:jedi#rename_command = "<leader>kr"
  let g:jedi#documentation_command = "<leader>kk"
  let g:jedi#completions_command = "<C-Space>"
  let g:jedi#popup_on_dot = 0
  autocmd FileType python let b:did_ftplugin = 1
'''

[[plugins]]
repo = 'neomake/neomake'
on_ft = ['python']
hook_source = '''
  autocmd! BufEnter,BufWritePost * Neomake
  let g:neomake_python_enabled_makers = ['python', 'flake8']
'''

[[plugins]]
repo = 'tell-k/vim-autopep8'
on_ft = ['python']
hook_source = '''
augroup autopep8
	autocmd!
	autocmd FileType python let g:syntastic_python_checkers = ['pyflakes', 'pep8']
	autocmd FileType python nnoremap <s-f> :Autopep8<cr>
augroup END
'''

